---
# vars file for osp.servers
vmstate: present

osp_servers:
  - { name: 'app1', meta_group: 'apps', meta_env: 'QA', flavor: 'm2.small', key: 'ansible_ssh', int_net: 'int_network', ext_net: 'ext_network', image: 'rhel-guest', sg: 'apps' }
  - { name: 'app2', meta_group: 'apps', meta_env: 'QA', flavor: 'm2.small', key: 'ansible_ssh', int_net: 'int_network', ext_net: 'ext_network', image: 'rhel-guest', sg: 'apps' }
  - { name: 'frontend', meta_group: 'frontends', meta_env: 'QA', flavor: 'm2.small', key: 'ansible_ssh', int_net: 'int_network', ext_net: 'ext_network', image: 'rhel-guest', sg: 'frontend' }
  - { name: 'db', meta_group: 'appdbs', meta_env: 'QA', flavor: 'm2.small', key: 'ansible_ssh', int_net: 'int_network', ext_net: 'ext_network', image: 'rhel-guest', sg: 'db' }

ssh_key_pub_url: http://www.opentlc.com/download/ansible_bootcamp/openstack_keys/openstack.pub
repo_internal: http://www.opentlc.com/download/ansible_bootcamp/repo/internal.repo


# osp_servers:
#   frontend:
#     name: frontend
#     state: present
#     image: rhel-guest
#     key_name: ansible_ssh
#     flavor: m2.small
#     security_group: frontend
#     meta:
#       - { group: frontends, deployment_name: QA}
#   app1:
#     name: app1
#     state: present
#     image: rhel-guest
#     key_name: ansible_ssh
#     flavor: m2.small
#     security_group: apps
#     meta:
#       - { group: apps, deployment_name: QA}
#   app2:
#     name: app2
#     state: present
#     image: rhel-guest
#     key_name: ansible_ssh
#     flavor: m2.small
#     security_group: apps
#     meta:
#       - { group: apps, deployment_name: QA}
#   db:
#     name: db
#     state: present
#     image: rhel-guest
#     key_name: ansible_ssh
#     flavor: m2.small
#     security_group: db
#     meta:
#       - { group: appdbs, deployment_name: QA}
