---

# tasks file for osp-servers
- name: Create new vm instances, attach network, pass metadata
  os_server:
    cloud: ospcloud
    state: "{{ vmstate }}"
    name: "{{ item.name }}"
    meta:
      group: "{{ item.meta_group }}"
      deployment_name: "{{ item.meta_env }}"
    flavor: "{{ item.flavor }}"
    key_name: "{{ item.key }}"
    nics:
      - net-name: "{{ item.int_net }}"
    image: "{{ item.image }}"
    security_groups: "{{ item.sg }}"
    userdata: |
      #!/bin/bash
      curl -o /tmp/openstack.pub "{{ ssh_key_pub_url }}"
      cat /tmp/openstack.pub >> /home/cloud-user/.ssh/authorized_keys
      curl -o /tmp/internal.repo "{{ repo_internal }}"
      cp /tmp/internal.repo /etc/yum.repos.d/internal.repo
  loop: "{{ os_servers }}"

- name: Add floating IP to Servers
  os_floating_ip:
    cloud: ospcloud
    state: present
    reuse: yes
    server: "{{ item.name }}"
    network: "{{ item.ext_net }}"
    wait: yes
    timeout: 180
  loop: "{{ osp_servers }}"
  register: instancefloatingip

- name: Wait for server to be available
  wait_for:
    host: "{{ item.floating_ip.floating_ip_address }}"
    port: 22
    search_regex: OpenSSH
    timeout: 300
  loop: "{{ instancefloatingip.results }}"
  delegate_to: "{{ inventory_hostname }}"
