---
# tasks file for app-tier

- name: install tomcat
  package:
    name: "{{ package }}"
    state: latest

- name: enable tomcat at boot
  service:
    name: "{{ package }}"
    enabled: yes

- name: create tomcat webroot directory
  file:
    path: "{{ webroot }}"
    state: directory

- name: copy static index.html to tomcat "{{ webroot }}"
  template:
    src: index.html.j2
    dest: "{{ webroot }}/index.html"
    mode: 0644
  notify: start tomcat
